services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: brainshare-mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: brainshare
      MONGODB_INITDB_ROOT_PASSWORD: brainshare
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config:
